---
title: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5-LibC++
permalink: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5-LibC++.html
tags: data
layout: ci_results
date: 2015-05-01 04:28:27
unhandled_failure: false
build_error_count: 0
build_warning_count: 0
package_error_count: 0
package_warning_count: 0
test_count: 346
test_passed_count: 2
repository: ChaiScript/ChaiScript
compiler: clang
compiler_version: 3.5
architecture: 
os: Linux
os_release: Ubuntu-14.04
is_release: false
release_packaged: false
packaging_skipped: true
package_name: 
tag_name: 
commit_sha: d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1
branch_name: parsing_reorg
test_run: true
pull_request_issue_id: ""
pull_request_base_repository: 
pull_request_base_ref: 
device_id: x86_64-Linux-Ubuntu-14.04-clang-3.5-LibC++
pending: false
analyze_only: false
build_time: 154.388451755
test_time: 16.563088323
package_time: 
install_time: 
results_repository: ChaiScript/ChaiScript-BuildResults
machine_name: jason-VirtualBox
machine_ip: 10.0.2.15
coverage_enabled: false
coverage_pass_limit: 90
coverage_warn_limit: 75
coverage_lines: 0
coverage_total_lines: 0
coverage_functions: 0
coverage_total_functions: 0
coverage_url: 
asset_url: 
---

{
  "build_results": [

  ],
  "test_results": [
    {
      "name": "3.x/bind.chai",
      "status": "failed",
      "time": "0.228403",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bind2.chai",
      "status": "failed",
      "time": "0.235469",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/block_start.chai",
      "status": "failed",
      "time": "0.231315",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/break_while.chai",
      "status": "failed",
      "time": "0.326881",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "version_check",
      "status": "failed",
      "time": "0.344879",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/assign_const.chai",
      "status": "failed",
      "time": "0.468277",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/collate.chai",
      "status": "failed",
      "time": "0.201688",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_lt.chai",
      "status": "failed",
      "time": "0.194274",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bool_not.chai",
      "status": "failed",
      "time": "0.535952",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_gt.chai",
      "status": "failed",
      "time": "0.199071",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/char_init.chai",
      "status": "failed",
      "time": "0.206417",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/classification.chai",
      "status": "failed",
      "time": "0.228235",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/const_range_test.chai",
      "status": "failed",
      "time": "0.207264",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_double_string.chai",
      "status": "failed",
      "time": "0.205258",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_int_string.chai",
      "status": "failed",
      "time": "0.225565",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_double.chai",
      "status": "failed",
      "time": "0.219758",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_int.chai",
      "status": "failed",
      "time": "0.228798",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/concat.chai",
      "status": "failed",
      "time": "0.276653",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/dispatch_functions.chai",
      "status": "failed",
      "time": "0.248662",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop.chai",
      "status": "failed",
      "time": "0.304229",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop_while.chai",
      "status": "failed",
      "time": "0.303051",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/deep_array_lookup.chai",
      "status": "failed",
      "time": "0.308739",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/empty.chai",
      "status": "failed",
      "time": "0.300948",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval.chai",
      "status": "failed",
      "time": "0.20831",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/equ_shortform.chai",
      "status": "failed",
      "time": "0.498444",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_guards.chai",
      "status": "failed",
      "time": "0.220839",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_finally.chai",
      "status": "failed",
      "time": "0.222979",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception.chai",
      "status": "failed",
      "time": "0.226287",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval_error.chai",
      "status": "failed",
      "time": "0.231961",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/even.chai",
      "status": "failed",
      "time": "0.249636",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/foldl.chai",
      "status": "failed",
      "time": "0.215115",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_range.chai",
      "status": "failed",
      "time": "0.20489",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/float.chai",
      "status": "failed",
      "time": "0.218683",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for.chai",
      "status": "failed",
      "time": "0.213679",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/filter.chai",
      "status": "failed",
      "time": "0.236941",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each.chai",
      "status": "failed",
      "time": "0.223189",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_array_adjacent.chai",
      "status": "failed",
      "time": "0.217045",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_retro.chai",
      "status": "failed",
      "time": "0.219641",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_introspection.chai",
      "status": "failed",
      "time": "0.223798",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_else.chai",
      "status": "failed",
      "time": "0.164113",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif_else.chai",
      "status": "failed",
      "time": "0.170221",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_reassignment.chai",
      "status": "failed",
      "time": "0.403705",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if.chai",
      "status": "failed",
      "time": "0.179552",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/generate_range.chai",
      "status": "failed",
      "time": "0.400011",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif.chai",
      "status": "failed",
      "time": "0.172228",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/global_const_in_module.chai",
      "status": "failed",
      "time": "0.203879",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.230771",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.266185",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/index_operator.chai",
      "status": "failed",
      "time": "0.283712",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval.chai",
      "status": "failed",
      "time": "0.276137",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_back.chai",
      "status": "failed",
      "time": "0.197825",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval_more.chai",
      "status": "failed",
      "time": "0.481708",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/inheritance.chai",
      "status": "failed",
      "time": "0.488898",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_front.chai",
      "status": "failed",
      "time": "0.196946",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/lambda.chai",
      "status": "failed",
      "time": "0.200967",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/join.chai",
      "status": "failed",
      "time": "0.204498",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/is_undef.chai",
      "status": "failed",
      "time": "0.245639",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/malformed_inline_map.chai",
      "status": "failed",
      "time": "0.209383",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_access.chai",
      "status": "failed",
      "time": "0.201181",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/loop_inner_outer.chai",
      "status": "failed",
      "time": "0.218028",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/load_module.chai",
      "status": "failed",
      "time": "0.220367",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map.chai",
      "status": "failed",
      "time": "0.218463",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_inplace_init.chai",
      "status": "failed",
      "time": "0.504739",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_div.chai",
      "status": "failed",
      "time": "0.353676",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_inc.chai",
      "status": "failed",
      "time": "0.345598",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add_mixed.chai",
      "status": "failed",
      "time": "0.389319",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mod.chai",
      "status": "failed",
      "time": "0.375357",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add.chai",
      "status": "failed",
      "time": "0.521558",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_dec.chai",
      "status": "failed",
      "time": "0.51726",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_negate.chai",
      "status": "failed",
      "time": "0.208094",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_sub.chai",
      "status": "failed",
      "time": "0.204259",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_paren.chai",
      "status": "failed",
      "time": "0.206368",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mult.chai",
      "status": "failed",
      "time": "0.210889",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/max.chai",
      "status": "failed",
      "time": "0.219768",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd2.chai",
      "status": "failed",
      "time": "0.192403",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd1.chai",
      "status": "failed",
      "time": "0.202437",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/min.chai",
      "status": "failed",
      "time": "0.2056",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/method_sugar.chai",
      "status": "failed",
      "time": "0.207798",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/multiline.chai",
      "status": "failed",
      "time": "0.19538",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/memberscope.chai",
      "status": "failed",
      "time": "0.237818",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_method_guards.chai",
      "status": "failed",
      "time": "0.283942",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr.chai",
      "status": "failed",
      "time": "0.341837",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_clone.chai",
      "status": "failed",
      "time": "0.333953",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/number_formats.chai",
      "status": "failed",
      "time": "0.343959",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr_same_name.chai",
      "status": "failed",
      "time": "0.363007",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_constructor_guards.chai",
      "status": "failed",
      "time": "0.355491",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload2.chai",
      "status": "failed",
      "time": "0.22405",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/odd.chai",
      "status": "failed",
      "time": "0.228536",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload.chai",
      "status": "failed",
      "time": "0.225875",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_float.chai",
      "status": "failed",
      "time": "0.220592",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_eq.chai",
      "status": "failed",
      "time": "0.275437",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_int.chai",
      "status": "failed",
      "time": "0.513574",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_2.chai",
      "status": "failed",
      "time": "0.285606",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.291593",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_1.chai",
      "status": "failed",
      "time": "0.288366",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pair.chai",
      "status": "failed",
      "time": "0.316993",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_3.chai",
      "status": "failed",
      "time": "0.301806",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_find.chai",
      "status": "failed",
      "time": "0.182964",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range.chai",
      "status": "failed",
      "time": "0.192881",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_back.chai",
      "status": "failed",
      "time": "0.191671",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/product.chai",
      "status": "failed",
      "time": "0.1967",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/ref_equal.chai",
      "status": "failed",
      "time": "0.258081",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_inplace.chai",
      "status": "failed",
      "time": "0.262681",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_contains.chai",
      "status": "failed",
      "time": "0.450429",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reflection_test.chai",
      "status": "failed",
      "time": "0.264444",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retroretro.chai",
      "status": "failed",
      "time": "0.256913",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retro.chai",
      "status": "failed",
      "time": "0.387341",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/return.chai",
      "status": "failed",
      "time": "0.215009",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/shift.chai",
      "status": "failed",
      "time": "0.230983",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_charptr.chai",
      "status": "failed",
      "time": "0.243837",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_concat.chai",
      "status": "failed",
      "time": "0.239549",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/runtime_error.chai",
      "status": "failed",
      "time": "0.251549",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reduce.chai",
      "status": "failed",
      "time": "0.546361",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.229315",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_of.chai",
      "status": "failed",
      "time": "0.22645",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_of.chai",
      "status": "failed",
      "time": "0.232441",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find.chai",
      "status": "failed",
      "time": "0.240033",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/sum.chai",
      "status": "failed",
      "time": "0.179167",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_init.chai",
      "status": "failed",
      "time": "0.408356",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.422207",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_default.chai",
      "status": "failed",
      "time": "0.181772",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_rfind.chai",
      "status": "failed",
      "time": "0.197805",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_break.chai",
      "status": "failed",
      "time": "0.185694",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_literal_access.chai",
      "status": "failed",
      "time": "0.32148",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.17421",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take.chai",
      "status": "failed",
      "time": "0.172939",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/type_info.chai",
      "status": "failed",
      "time": "0.171856",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_empty.chai",
      "status": "failed",
      "time": "0.19021",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru.chai",
      "status": "failed",
      "time": "0.188861",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take_while.chai",
      "status": "failed",
      "time": "0.203009",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.251471",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/use.chai",
      "status": "failed",
      "time": "0.273112",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_inplace_init.chai",
      "status": "failed",
      "time": "0.265991",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_erase_at.chai",
      "status": "failed",
      "time": "0.268858",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_access.chai",
      "status": "failed",
      "time": "0.308727",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_insert_at.chai",
      "status": "failed",
      "time": "0.300963",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.208941",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_back.chai",
      "status": "failed",
      "time": "0.211562",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip.chai",
      "status": "failed",
      "time": "0.247123",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_of_one.chai",
      "status": "failed",
      "time": "0.262181",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_empty.chai",
      "status": "failed",
      "time": "0.550525",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip_with.chai",
      "status": "failed",
      "time": "0.325122",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "block_start.chai",
      "status": "failed",
      "time": "0.338533",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "array_types.chai",
      "status": "failed",
      "time": "0.361162",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "assign_const.chai",
      "status": "failed",
      "time": "0.359648",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind.chai",
      "status": "failed",
      "time": "0.379932",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind2.chai",
      "status": "failed",
      "time": "0.372806",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "class.chai",
      "status": "failed",
      "time": "0.19662",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bool_not.chai",
      "status": "failed",
      "time": "0.211153",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_for.chai",
      "status": "failed",
      "time": "0.208346",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "char_init.chai",
      "status": "failed",
      "time": "0.200841",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_while.chai",
      "status": "failed",
      "time": "0.45919",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "collate.chai",
      "status": "failed",
      "time": "0.275241",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_gt.chai",
      "status": "failed",
      "time": "0.296533",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "classification.chai",
      "status": "failed",
      "time": "0.30323",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "concat.chai",
      "status": "failed",
      "time": "0.291724",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "const_range_test.chai",
      "status": "failed",
      "time": "0.300927",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_int_string.chai",
      "status": "failed",
      "time": "0.187036",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_lt.chai",
      "status": "failed",
      "time": "0.496493",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_while.chai",
      "status": "failed",
      "time": "0.193592",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_double_string.chai",
      "status": "failed",
      "time": "0.190378",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_for.chai",
      "status": "failed",
      "time": "0.196841",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_double.chai",
      "status": "failed",
      "time": "0.233642",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_int.chai",
      "status": "failed",
      "time": "0.211001",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "divide_by_zero_protection.chai",
      "status": "failed",
      "time": "0.206937",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop.chai",
      "status": "failed",
      "time": "0.205274",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "deep_array_lookup.chai",
      "status": "failed",
      "time": "0.210617",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dispatch_functions.chai",
      "status": "failed",
      "time": "0.208946",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop_while.chai",
      "status": "failed",
      "time": "0.487456",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "equ_shortform.chai",
      "status": "failed",
      "time": "0.281063",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_error.chai",
      "status": "failed",
      "time": "0.296288",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dynamic_object_dynamic_attrs.chai",
      "status": "failed",
      "time": "0.310567",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_file.chai",
      "status": "failed",
      "time": "0.293775",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval.chai",
      "status": "failed",
      "time": "0.329616",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "empty.chai",
      "status": "failed",
      "time": "0.334839",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_finally.chai",
      "status": "failed",
      "time": "0.224712",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_guards.chai",
      "status": "failed",
      "time": "0.223139",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed.chai",
      "status": "failed",
      "time": "0.22165",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception.chai",
      "status": "failed",
      "time": "0.348661",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "filter.chai",
      "status": "failed",
      "time": "0.17782",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed_2.chai",
      "status": "failed",
      "time": "0.180259",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "even.chai",
      "status": "failed",
      "time": "0.409782",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for.chai",
      "status": "failed",
      "time": "0.181034",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "float.chai",
      "status": "failed",
      "time": "0.184725",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "foldl.chai",
      "status": "failed",
      "time": "0.205757",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_array_adjacent.chai",
      "status": "failed",
      "time": "0.198042",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_attributes.chai",
      "status": "failed",
      "time": "0.207876",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_introspection.chai",
      "status": "failed",
      "time": "0.238775",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_range.chai",
      "status": "failed",
      "time": "0.252518",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_retro.chai",
      "status": "failed",
      "time": "0.250982",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each.chai",
      "status": "failed",
      "time": "0.391421",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_const_in_module.chai",
      "status": "failed",
      "time": "0.19071",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_members.chai",
      "status": "failed",
      "time": "0.269022",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_reassignment.chai",
      "status": "failed",
      "time": "0.265653",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "future.chai",
      "status": "failed",
      "time": "0.257839",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_redefinition.chai",
      "status": "failed",
      "time": "0.261504",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "generate_range.chai",
      "status": "failed",
      "time": "0.327964",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "hashbang.chai",
      "status": "failed",
      "time": "0.200428",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_in_script.chai",
      "status": "failed",
      "time": "0.203105",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif_else.chai",
      "status": "failed",
      "time": "0.217665",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_else.chai",
      "status": "failed",
      "time": "0.252194",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if.chai",
      "status": "failed",
      "time": "0.254058",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif.chai",
      "status": "failed",
      "time": "0.329385",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval.chai",
      "status": "failed",
      "time": "0.22486",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.215302",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.219146",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval_more.chai",
      "status": "failed",
      "time": "0.232816",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "inheritance.chai",
      "status": "failed",
      "time": "0.245026",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "index_operator.chai",
      "status": "failed",
      "time": "0.399538",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "join.chai",
      "status": "failed",
      "time": "0.203528",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "lambda.chai",
      "status": "failed",
      "time": "0.203175",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "load_module.chai",
      "status": "failed",
      "time": "0.209876",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_front.chai",
      "status": "failed",
      "time": "0.248263",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "is_undef.chai",
      "status": "failed",
      "time": "0.25669",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_back.chai",
      "status": "failed",
      "time": "0.282606",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map.chai",
      "status": "failed",
      "time": "0.212703",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "logical_short_circuiting.chai",
      "status": "failed",
      "time": "0.222497",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "loop_inner_outer.chai",
      "status": "failed",
      "time": "0.221103",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_count.chai",
      "status": "failed",
      "time": "0.198374",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "malformed_inline_map.chai",
      "status": "failed",
      "time": "0.219019",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_access.chai",
      "status": "failed",
      "time": "0.337386",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add.chai",
      "status": "failed",
      "time": "0.186193",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_inc.chai",
      "status": "failed",
      "time": "0.189013",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_dec.chai",
      "status": "failed",
      "time": "0.20128",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_inplace_init.chai",
      "status": "failed",
      "time": "0.211156",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add_mixed.chai",
      "status": "failed",
      "time": "0.205067",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_div.chai",
      "status": "failed",
      "time": "0.215644",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_negate.chai",
      "status": "failed",
      "time": "0.18735",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_paren.chai",
      "status": "failed",
      "time": "0.185893",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mod.chai",
      "status": "failed",
      "time": "0.193143",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_sub.chai",
      "status": "failed",
      "time": "0.202562",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mult.chai",
      "status": "failed",
      "time": "0.210502",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "max.chai",
      "status": "failed",
      "time": "0.33727",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_sugar.chai",
      "status": "failed",
      "time": "0.215854",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd1.chai",
      "status": "failed",
      "time": "0.221489",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "member_variable_access.chai",
      "status": "failed",
      "time": "0.250113",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_missing.chai",
      "status": "failed",
      "time": "0.244393",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "memberscope.chai",
      "status": "failed",
      "time": "0.248819",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "min.chai",
      "status": "failed",
      "time": "0.376829",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline_oper.chai",
      "status": "failed",
      "time": "0.337718",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_formats.chai",
      "status": "failed",
      "time": "0.324816",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline.chai",
      "status": "failed",
      "time": "0.34122",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "null_object_access.chai",
      "status": "failed",
      "time": "0.331066",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd2.chai",
      "status": "failed",
      "time": "0.471667",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_suffixes.chai",
      "status": "failed",
      "time": "0.447811",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr.chai",
      "status": "failed",
      "time": "0.215991",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_clone.chai",
      "status": "failed",
      "time": "0.206014",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_constructor_guards.chai",
      "status": "failed",
      "time": "0.198843",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_method_guards.chai",
      "status": "failed",
      "time": "0.209053",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr_same_name.chai",
      "status": "failed",
      "time": "0.255766",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload2.chai",
      "status": "failed",
      "time": "0.199562",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload.chai",
      "status": "failed",
      "time": "0.201055",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_scoping.chai",
      "status": "failed",
      "time": "0.194874",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_float.chai",
      "status": "failed",
      "time": "0.193766",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_int.chai",
      "status": "failed",
      "time": "0.189401",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "odd.chai",
      "status": "failed",
      "time": "0.390439",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_1.chai",
      "status": "failed",
      "time": "0.24192",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_2.chai",
      "status": "failed",
      "time": "0.25113",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pass_by_reference.chai",
      "status": "failed",
      "time": "0.283879",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_3.chai",
      "status": "failed",
      "time": "0.24211",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pair.chai",
      "status": "failed",
      "time": "0.288332",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.289281",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_contains.chai",
      "status": "failed",
      "time": "0.281365",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "product.chai",
      "status": "failed",
      "time": "0.300337",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_eq.chai",
      "status": "failed",
      "time": "0.301761",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_find.chai",
      "status": "failed",
      "time": "0.276772",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range.chai",
      "status": "failed",
      "time": "0.431146",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_back.chai",
      "status": "failed",
      "time": "0.429614",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reflection_test.chai",
      "status": "failed",
      "time": "0.219704",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retro.chai",
      "status": "failed",
      "time": "0.223199",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_inplace.chai",
      "status": "failed",
      "time": "0.228275",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retroretro.chai",
      "status": "failed",
      "time": "0.213972",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reduce.chai",
      "status": "failed",
      "time": "0.260448",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "shift.chai",
      "status": "failed",
      "time": "0.273211",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_charptr.chai",
      "status": "failed",
      "time": "0.287224",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "return.chai",
      "status": "failed",
      "time": "0.304018",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_concat.chai",
      "status": "failed",
      "time": "0.279253",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "runtime_error.chai",
      "status": "failed",
      "time": "0.420635",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "scoping.chai",
      "status": "failed",
      "time": "0.41908",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_of.chai",
      "status": "failed",
      "time": "0.178093",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.205908",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_of.chai",
      "status": "failed",
      "time": "0.202182",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find.chai",
      "status": "failed",
      "time": "0.217974",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.245479",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_rfind.chai",
      "status": "failed",
      "time": "0.22747",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_size.chai",
      "status": "failed",
      "time": "0.221765",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_substr.chai",
      "status": "failed",
      "time": "0.219561",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "sum.chai",
      "status": "failed",
      "time": "0.212957",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_init.chai",
      "status": "failed",
      "time": "0.234343",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_literal_access.chai",
      "status": "failed",
      "time": "0.253392",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_empty.chai",
      "status": "failed",
      "time": "0.2537",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru.chai",
      "status": "failed",
      "time": "0.251666",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.276758",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "system_introspection.chai",
      "status": "failed",
      "time": "0.268521",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_break.chai",
      "status": "failed",
      "time": "0.427588",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_default.chai",
      "status": "failed",
      "time": "0.425972",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take_while.chai",
      "status": "failed",
      "time": "0.235108",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "temporary_lifetime.chai",
      "status": "failed",
      "time": "0.231466",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "ternary_condition.chai",
      "status": "failed",
      "time": "0.227793",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "type_info.chai",
      "status": "failed",
      "time": "0.225675",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take.chai",
      "status": "failed",
      "time": "0.264373",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions.chai",
      "status": "failed",
      "time": "0.189494",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions_2.chai",
      "status": "failed",
      "time": "0.218203",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_decl.chai",
      "status": "failed",
      "time": "0.210494",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_ref_decl.chai",
      "status": "failed",
      "time": "0.208427",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "variable_redefinition.chai",
      "status": "failed",
      "time": "0.214535",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "use.chai",
      "status": "failed",
      "time": "0.465863",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_inplace_init.chai",
      "status": "failed",
      "time": "0.270296",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_insert_at.chai",
      "status": "failed",
      "time": "0.318364",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.314333",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_one.chai",
      "status": "failed",
      "time": "0.308082",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_access.chai",
      "status": "failed",
      "time": "0.326236",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_erase_at.chai",
      "status": "failed",
      "time": "0.341907",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_push_back.chai",
      "status": "failed",
      "time": "0.18606",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_push_empty.chai",
      "status": "failed",
      "time": "0.198375",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip.chai",
      "status": "failed",
      "time": "0.196685",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip_with.chai",
      "status": "failed",
      "time": "0.190204",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_suffixed_numbers.chai",
      "status": "failed",
      "time": "0.204087",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "C++11 Lambdas Can Be Registered",
      "status": "failed",
      "time": "0.02248",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nC++11 Lambdas Can Be Registered\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:33\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:33: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "33",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.224972",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Dynamic_Object attributes can be shared with C++",
      "status": "failed",
      "time": "0.0184319",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nDynamic_Object attributes can be shared with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:52\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:52: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "52",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function objects can be created from chaiscript functions",
      "status": "failed",
      "time": "0.017019",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction objects can be created from chaiscript functions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:79\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:79: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "79",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "ChaiScript can be created and destroyed on heap",
      "status": "failed",
      "time": "0.014688",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nChaiScript can be created and destroyed on heap\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:94\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:94: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "94",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Test automatic arithmetic conversions",
      "status": "failed",
      "time": "0.0166919",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest automatic arithmetic conversions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:126\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:126: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "126",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Generic exception handling with C++",
      "status": "failed",
      "time": "0.0134861",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nGeneric exception handling with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:167\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:167: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "167",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw an int",
      "status": "failed",
      "time": "0.0380039",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow an int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:180\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:180: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "180",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw int or double",
      "status": "failed",
      "time": "0.035342",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow int or double\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:192\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:192: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "192",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw a runtime_error",
      "status": "failed",
      "time": "0.033299",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow a runtime_error\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:204\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:204: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "204",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw unhandled type",
      "status": "failed",
      "time": "0.0320199",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow unhandled type\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:224\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:224: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "224",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "No unexpected exceptions leak",
      "status": "failed",
      "time": "0.0275578",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nNo unexpected exceptions leak\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:253\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:253: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "253",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function ordering",
      "status": "failed",
      "time": "0.016258",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction ordering\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:316\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:316: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "316",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Functor cast",
      "status": "failed",
      "time": "0.012655",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunctor cast\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:339\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:339: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "339",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Short comparison with int",
      "status": "failed",
      "time": "0.023304",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nShort comparison with int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:405\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:405: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "405",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Test lookup of type names",
      "status": "failed",
      "time": "0.020617",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest lookup of type names\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:428\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:428: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "428",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Simultaneous ChaiScript tests",
      "status": "failed",
      "time": "0.0194249",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSimultaneous ChaiScript tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:454\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:454: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "454",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Utility_Test utility class wrapper",
      "status": "failed",
      "time": "0.0139561",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nUtility_Test utility class wrapper\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:488\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:488: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "488",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object lifetime tests",
      "status": "failed",
      "time": "0.015471",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:637\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:637: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "637",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object copy counts",
      "status": "failed",
      "time": "0.017843",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject copy counts\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:581\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:581: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "581",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Set and restore chai state",
      "status": "failed",
      "time": "0.0318871",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSet and restore chai state\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:359\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:359: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "359",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object lifetime test 2",
      "status": "failed",
      "time": "0.0209072",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime test 2\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:697\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5LC++/unittests/compiled_tests.cpp:697: FAILED:\ndue to unexpected exception with message:\n  stod: no conversion\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "697",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Boxed_Cast_Test",
      "status": "passed",
      "time": "0.027585",
      "output": null,
      "parsed_errors": [

      ]
    },
    {
      "name": "Type_Info_Test",
      "status": "passed",
      "time": "0.0256171",
      "output": "Size of Type_Info 24\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Integer_Literal_Test",
      "status": "failed",
      "time": "0.166251",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "MultiFile_Test",
      "status": "failed",
      "time": "0.16703",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Multithreaded_Test",
      "status": "failed",
      "time": "0.18306",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "C_Linkage_Test",
      "status": "failed",
      "time": "0.188949",
      "output": "terminating with uncaught exception of type std::invalid_argument: stod: no conversion\n",
      "parsed_errors": [

      ]
    }
  ],
  "failure": null,
  "package_results": [

  ]
}

